### PR TITLE
Feature#9 create flight reservation

### LINKED ISSUE #9: Create a flight reservation
# REQUIREMENTS
As a user, on the first screen I will select the place of my flight departure.

On the second screen I will select where I want to fly.

In the third screen I will select the departure date of this flight.

On the fourth screen select the number of passengers to board.

And in the last screen it should show me a message indicating that the request was received.
At the end, each screen must contain a button that allows me to go to the next screen, except the last one where the option to finish should appear.

# DESIGN
image

# Acceptance Criteria
List all required acceptance criteria
- [ ] Question of each screen
- [ ] Option that is provided to the user to choose
- [ ] The Button, which should allow the selected information to be taken to the next window.

### PR DESCRIPTION
**Pull request by Alonso-AS**
# Description
The windows that will need to be created in order to book a flight were created.
 In this pull request only the windows (front-end) were created, another Issue will be performed where a refactorization of the position of other windows, affecting this branch, is made, so its prompt validation is needed.

  ## Screenshots 
image
image
image
image
image
image

### CODE REVIEW

**Review by jkzasori — CHANGES_REQUESTED** [review]
You have some issues in codeClimate refactor and do push again 
image

**Review by jkzasori — APPROVED** [review]

**Comment by DiegoSpielzeug** [comment]
Lgtm

**Comment by DiegoSpielzeug** [comment]
Lgtm

**Comment by DiegoSpielzeug** [comment]
great!

**Review by DiegoSpielzeug — APPROVED** [review]

**Pull request merged**
